# Generated by Django 5.2.8 on 2025-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_ns', models.FloatField(verbose_name='Länge Nord/Süd [m]')),
                ('width_ow', models.FloatField(verbose_name='Breite Ost/West [m]')),
                ('storeys', models.IntegerField(verbose_name='Geschosse')),
                ('room_height', models.FloatField(verbose_name='Raumhöhe [m]')),
                ('u_wall', models.FloatField(verbose_name='U-Wert Außenwand [W/m²K]')),
                ('u_roof', models.FloatField(verbose_name='U-Wert Dach [W/m²K]')),
                ('u_floor', models.FloatField(verbose_name='U-Wert Kellerdecke [W/m²K]')),
                ('u_window', models.FloatField(verbose_name='U-Wert Fenster [W/m²K]')),
                ('setpoint_temp', models.FloatField(verbose_name='Solltemperatur [°C]')),
            ],
        ),
    ]
