# Generated by Django 5.2.8 on 2025-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='air_change_rate',
            field=models.FloatField(default=0.5, verbose_name='Luftwechselrate n [1/h]'),
        ),
        migrations.AddField(
            model_name='building',
            name='degree_days',
            field=models.FloatField(default=3000, verbose_name='Heizgradtage HDD [K*d]'),
        ),
        migrations.AddField(
            model_name='building',
            name='g_e',
            field=models.FloatField(default=0.6, verbose_name='g-Wert Ost'),
        ),
        migrations.AddField(
            model_name='building',
            name='g_n',
            field=models.FloatField(default=0.6, verbose_name='g-Wert Nord'),
        ),
        migrations.AddField(
            model_name='building',
            name='g_s',
            field=models.FloatField(default=0.6, verbose_name='g-Wert Süd'),
        ),
        migrations.AddField(
            model_name='building',
            name='g_w',
            field=models.FloatField(default=0.6, verbose_name='g-Wert West'),
        ),
        migrations.AddField(
            model_name='building',
            name='person_density',
            field=models.FloatField(default=20, verbose_name='Personendichte [m²/Person]'),
        ),
        migrations.AddField(
            model_name='building',
            name='persons',
            field=models.IntegerField(default=24, verbose_name='Personen'),
        ),
        migrations.AddField(
            model_name='building',
            name='window_share_e',
            field=models.FloatField(default=50, verbose_name='Fensteranteil Ost [%]'),
        ),
        migrations.AddField(
            model_name='building',
            name='window_share_n',
            field=models.FloatField(default=50, verbose_name='Fensteranteil Nord [%]'),
        ),
        migrations.AddField(
            model_name='building',
            name='window_share_s',
            field=models.FloatField(default=50, verbose_name='Fensteranteil Süd [%]'),
        ),
        migrations.AddField(
            model_name='building',
            name='window_share_w',
            field=models.FloatField(default=50, verbose_name='Fensteranteil West [%]'),
        ),
    ]
