# Generated by Django 5.2.8 on 2025-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_building_result_h_t_building_result_h_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='pv_roof_share',
            field=models.FloatField(default=50, verbose_name='PV-Anteil Dachfläche [%]'),
        ),
        migrations.AddField(
            model_name='building',
            name='pv_self_consumption_share',
            field=models.FloatField(default=70, verbose_name='PV-Eigenverbrauchsanteil [%]'),
        ),
        migrations.AddField(
            model_name='building',
            name='pv_specific_yield',
            field=models.FloatField(default=180, verbose_name='PV-spezifischer Ertrag [kWh/m²*a]'),
        ),
        migrations.AddField(
            model_name='building',
            name='result_Q_PV_off',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='result_Q_PV_on',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='result_Q_PV_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
